---
version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    channel: eslint-6
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-80
checks:
  return-statements:
    config:
      threshold: 5
exclude_patterns:
- config/
- db/
- doc/
- script/
- spec/
