extends: stylelint-config-standard
plugins:
- stylelint-declaration-strict-value
#- stylelint-group-selectors
- stylelint-order
- stylelint-scss

rules:
  no-descending-specificity: null
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
#  plugin/stylelint-group-selectors: true

  scale-unlimited/declaration-strict-value:
  - - "/color$/"
  - ignoreValues:
    - inherit
    - transparent
    - unset

  at-rule-empty-line-before: null

  color-hex-case: upper
  color-hex-length: long

  comment-empty-line-before: null
  custom-property-empty-line-before: null

  declaration-block-semicolon-newline-after: always
  #declaration-colon-newline-after: always-multi-line
  declaration-empty-line-before: null

  #function-comma-newline-after: always-multi-line
  #function-max-empty-lines: 0
  #function-name-case: lower
  #function-parentheses-newline-inside: always-multi-line
  #function-parentheses-space-inside: never-single-line

  length-zero-no-unit: null
  # max-empty-lines: 1

  # media-feature-name-case: lower
  # media-query-list-comma-newline-after: always-multi-line

  # number-leading-zero: always
  # number-no-trailing-zeros: true

  # property-case: lower

  #rule-empty-line-before:
  #- always-multi-line
  #- except:
  #  - first-nested
  #  ignore:
  #  - after-comment

  selector-list-comma-newline-after: null
  # selector-pseudo-class-case: lower
  # selector-pseudo-element-case: lower
  # selector-pseudo-element-colon-notation: double
  # selector-type-case: lower

  # unit-case: lower

  # value-keyword-case: lower
  # value-list-comma-newline-after: always-multi-line
  # value-list-max-empty-lines: 0

ignoreFiles:
- 'app/assets/stylesheets/normalize.scss'
