language: ruby
rvm:
 - 2.3.3
env:
- CI=true
services:
  - redis-server
  - postgresql
before_script:
  - psql -c 'create database glowfic_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
branches:
  only:
  - master
