language: ruby
rvm:
 - 2.4.2
env:
- CI=true
services:
  - redis-server
  - postgresql
cache: bundler
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database glowfic_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rspec spec
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 1e0c6dba9930e839038860b6d73301226c821937f57ed35d06fc0e4b7bddf5f6
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    secure: "e5z37tW+Ew8FuqTsicGVuzEgGyHK9UGNiZzlxtv7On65oXOOuVWujiUbbXRRPG9pjftFLEHnNARBXE2mxEVoc+AkgjzxkfngebicdkKByf85MQGuxnDb8V0dKkoU08Z0QMtggqKye3MWZ5sv0BYJKGlzdFyFWkLDn6GG8wIk5npyDaxIjA6t2W97mdAr4RYQSsF6xejhrfr4HZ7FxloHKFqf2Duosno/BD7hQK+Cj95IOCXP3uekAs0B3ZI2aBzO6e3u0X6WjAv8bz/FT9L1E7QmoRGZ+KkhZLxQfzl8aEKmnqA4NTgfKAjY6m6C2cBtRaaS9+Q16MrYoMttLzP2/+KMc/cEPoSunhTdCutKsKz5XKbE/2QasyKwS3uKmIIHlUPb7NGS9XhzbCie/0J2UZr4UH6+ZT4a6YipjmGL/EvgS9XI0PYLupAFBFhCm5/Mb6o6rPs7EiJKYggXKSGL2JEo+8BvPUuWQKrrHRCHUWfs/7q7zLd48Y7VhBW82uBC0GS8cTtdrvd7yUqevNK19RkU4XcegPxqpnltsKZIRjIN33h6mSNDTPOssrJA3BAJPF+h2lO4gP1e3zyD/DmC5eLWtdhoDjJfSaZi9s5E9BqTvfV0bLjUcuEDW6UHXpKhYDfqc+8nLWHAUh2Tl5Eucrv1cFF73h43FHuFZ+zfO7k="
