version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - bundler-volume:/usr/local/bundle
    links:
      - redis
      - postgres
    working_dir: /code
    command: bin/rails s
    environment:
      - REDIS_URL=redis://redis
      - GLOWFIC_DATABASE_HOST=postgres
      - GLOWFIC_DATABASE_USER=postgres
      - GLOWFIC_DATABASE_PASS=postgres
      - BIND_HOST=0.0.0.0
  redis:
    image: redis:4.0-alpine
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:11-alpine
    volumes:
      - "./db/storage/:/var/lib/postgresql/data"

volumes:
  bundler-volume:
